### ISSUE TITLE
sezione prezzi

### ISSUE THREAD

**Issue by stefanodp91** [openrecordz/landing-page#15]
aggiungere pagina prezzi (gratis fino a 10 datasets)

pagamento -> contattaci

**Comment by alessandro-giovinazzo** [comment]
Ok, fatto
http://www.openrecordz.com/prezzi/

**Comment by andrealeo83** [comment]
il footer della pagina si vede male

**Comment by alessandro-giovinazzo** [comment]
Ok. Vedo che succede anche nelle pagine della documentazione e saltuariamente si verifica anche in Home. Magari chiedo velocemente supporto a Stefano prima di procedere alla risoluzione
